#!/usr/bin/env python3
# Copyright (c) 2026 Filip Marić. See LICENCE.

"""Import exam applications from the HTML reports generated by Hypatia."""

from __future__ import annotations

import argparse
from html.parser import HTMLParser
import re
import sqlite3
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

import db as mydb
from group_metadata import infer_group_metadata


TERM_LABEL_PATTERNS = (
    (re.compile(r"^Септембар\s*2\s+(\d{4})$", re.IGNORECASE), lambda year: f"{year}.10"),
    (re.compile(r"^Септембар\s*1\s+(\d{4})$", re.IGNORECASE), lambda year: f"{year}.09"),
    (re.compile(r"^Јануар\s*1\s+(\d{4})$", re.IGNORECASE), lambda year: f"{year}.01"),
    (re.compile(r"^Јануар\s*2\s+(\d{4})$", re.IGNORECASE), lambda year: f"{year}.02"),
)


def _normalize(value) -> str:
    return " ".join(str(value or "").replace("\xa0", " ").split())


def _normalize_index(value) -> str:
    return re.sub(r"\s*/\s*", "/", _normalize(value))


class _ReportParser(HTMLParser):
    """Read the repeated report pages without requiring an HTML dependency."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.pages = []
        self._details = False
        self._details_lines = []
        self._students = False
        self._row = None
        self._cell = None
        self._rows = []

    @staticmethod
    def _has_id(attrs, expected):
        return dict(attrs).get("id") == expected

    def handle_starttag(self, tag, attrs):
        if tag == "td" and self._has_id(attrs, "details"):
            self._details = True
            self._details_lines = []
        elif tag == "tbody" and self._has_id(attrs, "students-list"):
            self._students = True
            self._rows = []
        elif self._students and tag == "tr":
            self._row = []
        elif self._students and self._row is not None and tag == "td":
            self._cell = []
        elif self._details and tag == "br":
            self._details_lines.append("\n")

    def handle_endtag(self, tag):
        if self._students and tag == "td" and self._cell is not None:
            self._row.append("".join(self._cell))
            self._cell = None
        elif self._students and tag == "tr" and self._row is not None:
            if self._row:
                self._rows.append(self._row)
            self._row = None
        elif self._students and tag == "tbody":
            self._students = False
            self.pages.append({
                "details": "".join(self._details_lines),
                "rows": self._rows,
            })
        elif self._details and tag == "td":
            self._details = False

    def handle_data(self, data):
        if self._details:
            self._details_lines.append(data)
        if self._students and self._cell is not None:
            self._cell.append(data)


def _parse_term_code(label: str) -> str:
    normalized = _normalize(label)
    for pattern, make_code in TERM_LABEL_PATTERNS:
        match = pattern.match(normalized)
        if match:
            return make_code(match.group(1))
    raise ValueError(
        f"Cannot infer term code from HTML label {normalized!r}; use --term-code"
    )


def _parse_page(page):
    lines = [_normalize(line) for line in page["details"].splitlines() if _normalize(line)]
    if len(lines) < 3:
        raise ValueError("A report page does not contain the expected details block")
    subject_line = lines[-1]
    match = re.search(r",\s*([^,]+?)\s*\(([^()]*)\)\s*,\s*([^,]+)$", subject_line)
    if match is None:
        raise ValueError(f"Cannot extract course code and group from {subject_line!r}")
    subject_name = _normalize(match.group(1))
    course_code = _normalize(match.group(2))
    group_name = _normalize(match.group(3))
    indexes = []
    for row in page["rows"]:
        if len(row) < 2:
            continue
        index = _normalize_index(row[1])
        if index:
            indexes.append(index)
    return {
        "term_label": lines[0],
        "subject_name": subject_name,
        "course_code": course_code,
        "group_name": group_name,
        "student_indexes": indexes,
    }


def _resolve_student(cur, student_index):
    row = cur.execute(
        "SELECT username FROM students WHERE student_index = ?",
        (_normalize_index(student_index),),
    ).fetchone()
    if row is None:
        raise ValueError(f"unknown student index {student_index}")
    return row[0]


def _subject_candidates(cur, course_code):
    return cur.execute(
        """
        SELECT DISTINCT s.id, s.accreditation, s.module, s.name
        FROM course_subjects cs
        JOIN subjects s ON s.id = cs.subject_id
        WHERE cs.course_code = ? OR s.code = ?
        ORDER BY s.id
        """,
        (course_code, course_code),
    ).fetchall()


def _module_from_username(username):
    prefix = _normalize(username).lower()[:2]
    return {
        "ma": "МА",
        "ml": "МЛ",
        "mm": "ММ",
        "mp": "МП",
        "mr": "МР",
        "ms": "МС",
        "af": "АФ",
        "ai": "АИ",
        "mi": "И",
    }.get(prefix)


def _canonical_module(value):
    return {
        "M": "ММ",
        "R": "МР",
        "S": "МС",
        "P": "МП",
        "L": "МЛ",
        "F": "АФ",
        "I": "АИ",
    }.get(str(value or "").strip().upper(), value)


def _resolve_subject(cur, course_code, subject_name, group_name, username, semester_id):
    enrolled = cur.execute(
        """
        SELECT DISTINCT se.subject_id
        FROM student_enrollments se
        JOIN course_subjects cs ON cs.subject_id = se.subject_id
        JOIN subjects enrolled_subject ON enrolled_subject.id = se.subject_id
        WHERE se.student_username = ?
          AND se.semester_id = ?
          AND (cs.course_code = ? OR enrolled_subject.code = ?)
        ORDER BY se.subject_id
        """,
        (username, semester_id, course_code, course_code),
    ).fetchall()
    enrolled_ids = {int(row[0]) for row in enrolled}
    if len(enrolled_ids) == 1:
        return enrolled_ids.pop()

    metadata = infer_group_metadata(group_name)
    candidates = _subject_candidates(cur, course_code)
    named = [
        row for row in candidates
        if _normalize(row[3]).casefold() == _normalize(subject_name).casefold()
    ]
    if named:
        candidates = named
    module = _canonical_module(metadata[1]) or _module_from_username(username)
    if module is None:
        candidates = [row for row in candidates if row[2] in (None, "")]
    else:
        candidates = [
            row for row in candidates
            if str(row[2]).strip() == str(module).strip()
        ]
    if len(candidates) > 1 and metadata[2] is not None:
        accredited = [
            row for row in candidates
            if str(row[1]).strip() == str(metadata[2]).strip()
        ]
        if accredited:
            candidates = accredited
    if len(candidates) == 1:
        return int(candidates[0][0])
    if not candidates and len(_subject_candidates(cur, course_code)) == 1:
        return int(_subject_candidates(cur, course_code)[0][0])
    raise ValueError(
        f"ambiguous subject for course {course_code}, group {group_name}, student {username}"
    )


def _ensure_term(cur, term_code, start_date, end_date, semester_id):
    existing = cur.execute(
        "SELECT term_code, semester_id FROM exam_terms WHERE term_code = ?",
        (term_code,),
    ).fetchone()
    if existing is not None:
        return int(existing[1])
    if not start_date or not end_date:
        raise ValueError(
            f"Exam term {term_code} is missing; provide --start-date and --end-date"
        )
    if semester_id is None:
        row = cur.execute(
            """
            SELECT id FROM semesters
            WHERE start_date <= ? AND end_date >= ?
            ORDER BY start_date DESC, end_date ASC, id DESC
            LIMIT 1
            """,
            (start_date, end_date),
        ).fetchone()
        if row is None:
            raise ValueError(
                f"Cannot resolve semester for exam term {term_code} ({start_date}..{end_date})"
            )
        semester_id = int(row[0])
    cur.execute(
        """
        INSERT INTO exam_terms (term_code, start_date, end_date, semester_id)
        VALUES (?, ?, ?, ?)
        """,
        (term_code, start_date, end_date, semester_id),
    )
    return semester_id


def main(argv=None):
    parser = argparse.ArgumentParser(description="Import Hypatia HTML exam application reports.")
    parser.add_argument("database", help="SQLite database path")
    parser.add_argument("html_file", help="HTML report generated by Hypatia")
    parser.add_argument("--term-code", help="Override the inferred exam term code")
    parser.add_argument("--start-date", help="Start date when creating a missing term (YYYY-MM-DD)")
    parser.add_argument("--end-date", help="End date when creating a missing term (YYYY-MM-DD)")
    parser.add_argument("--semester-id", type=int, help="Semester id for a newly created term")
    args = parser.parse_args(argv)

    html_path = Path(args.html_file).expanduser()
    if not html_path.exists():
        print(f"HTML file not found: {html_path}")
        return 1

    parser_instance = _ReportParser()
    parser_instance.feed(html_path.read_text(encoding="utf-8-sig"))
    if not parser_instance.pages:
        print("ERROR: no report pages found")
        return 1

    parsed_pages = [_parse_page(page) for page in parser_instance.pages]
    term_code = args.term_code or _parse_term_code(parsed_pages[0]["term_label"])
    if any(page["term_label"] != parsed_pages[0]["term_label"] for page in parsed_pages):
        print("ERROR: HTML contains multiple exam-term labels")
        return 1

    conn = sqlite3.connect(args.database)
    conn.row_factory = sqlite3.Row
    try:
        with conn:
            mydb.ensure_exam_schedule_schema(conn)
            mydb.ensure_exam_application_schema(conn)
            cur = conn.cursor()
            semester_id = _ensure_term(
                cur, term_code, args.start_date, args.end_date, args.semester_id
            )

            desired = set()
            skipped = 0
            for page_number, page in enumerate(parsed_pages, start=1):
                for student_index in page["student_indexes"]:
                    try:
                        username = _resolve_student(cur, student_index)
                        subject_id = _resolve_subject(
                            cur,
                            page["course_code"],
                            page["subject_name"],
                            page["group_name"],
                            username,
                            semester_id,
                        )
                        desired.add((subject_id, username))
                    except ValueError as exc:
                        print(
                            f"SKIP\tpage={page_number}\tcourse={page['course_code']}"
                            f"\tstudent_index={student_index}\treason={exc}",
                            file=sys.stderr,
                        )
                        skipped += 1

            existing = {
                (int(row["subject_id"]), str(row["student_username"])): int(row["id"])
                for row in cur.execute(
                    "SELECT id, subject_id, student_username FROM exam_applications WHERE term_code = ?",
                    (term_code,),
                )
            }
            deleted = 0
            for key, application_id in existing.items():
                if key not in desired:
                    cur.execute("DELETE FROM exam_applications WHERE id = ?", (application_id,))
                    deleted += 1
            inserted = 0
            for subject_id, username in sorted(desired):
                if (subject_id, username) not in existing:
                    cur.execute(
                        """
                        INSERT INTO exam_applications (term_code, subject_id, student_username)
                        VALUES (?, ?, ?)
                        """,
                        (term_code, subject_id, username),
                    )
                    inserted += 1
        print(
            f"Synced exam applications for term {term_code}: "
            f"{inserted} inserted, {deleted} deleted, {len(desired) - inserted} unchanged, "
            f"{skipped} skipped from {html_path}."
        )
        return 0
    except Exception as exc:
        conn.rollback()
        print(f"ERROR: {exc}")
        return 1
    finally:
        conn.close()


if __name__ == "__main__":
    raise SystemExit(main())
